#!/bin/bash
cd "$(dirname "$0")"
echo - Building JavaScript

cat js/request.js js/time.js js/extraFunctions.js js/adBlock.js js/accessManager.js js/videoManager.js js/navBar.js js/app.js > dist/main.js

echo - Building CSS
cat css/main.css css/navBar.css > dist/main.css

cp -r images dist/images

echo \|-------------------\|
echo \| Finished Building \|
echo \|-------------------\|
